module.exports.URL= Object.freeze({   

  // UTTARAKHAND_CNR:""
  ALLAHABAD_ADVOCATE:"http://www.allahabadhighcourt.in/apps/status/index.php/party-name",
  ALLAHABAD_CASE:"http://www.allahabadhighcourt.in/apps/status/index.php/case-number",
  ALLAHABAD_CNR:"http://www.allahabadhighcourt.in/apps/status/index.php/party-name",
  ALLAHABAD_PARTY:"http://www.allahabadhighcourt.in/apps/status/index.php/party-name",
  ANDHRA_PRADESH_ADVOCATE:"https://services.ecourts.gov.in/ecourtindiaHC/cases/qs_civil_advocate.php?state_cd=2&dist_cd=1&court_code=1&stateNm=Andhra%20Pradesh",
  ANDHRA_PRADESH_CASE:"https://services.ecourts.gov.in/ecourtindiaHC/cases/case_no.php?state_cd=2&dist_cd=1&court_code=1&stateNm=Andhra%20Pradesh",
  ANDHRA_PRADESH_PARTY:"https://services.ecourts.gov.in/ecourtindiaHC/cases/ki_petres.php?state_cd=2&dist_cd=1&court_code=1&stateNm=Andhra%20Pradesh",
  BOMBAY_HOME:"https://bombayhighcourt.nic.in",
  CALCUTTA:"https://www.calcuttahighcourt.gov.in/Case-Status",
  CHHATTISGARH_ADVOCATE:"https://services.ecourts.gov.in/ecourtindiaHC/cases/qs_civil_advocate.php?state_cd=17&dist_cd=1&court_code=1&stateNm=Gujarat",
  CHHATTISGARH_CASE:"https://services.ecourts.gov.in/ecourtindiaHC/cases/case_no.php?state_cd=17&dist_cd=1&court_code=1&stateNm=Gujarat",
  CHHATTISGARH_PARTY:"https://services.ecourts.gov.in/ecourtindiaHC/cases/ki_petres.php?state_cd=17&dist_cd=1&court_code=1&stateNm=Gujarat",
  DELHI:"http://delhihighcourt.nic.in/case.asp",
  GUJRAT_ADVOCATE:"https://services.ecourts.gov.in/ecourtindiaHC/cases/qs_civil_advocate.php?state_cd=17&dist_cd=1&court_code=1&stateNm=Gujarat",
  GUJRAT_CASE:"https://services.ecourts.gov.in/ecourtindiaHC/cases/case_no.php?state_cd=17&dist_cd=1&court_code=1&stateNm=Gujarat",
  GUJRAT_PARTY:"https://services.ecourts.gov.in/ecourtindiaHC/cases/ki_petres.php?state_cd=17&dist_cd=1&court_code=1&stateNm=Gujarat",
  GUWAHATI_ADVOCATE:"https://services.ecourts.gov.in/ecourtindiaHC/cases/qs_civil_advocate.php?state_cd=6&dist_cd=1&court_code=1&stateNm=Assam",
  GUWAHATI_CASE:"https://services.ecourts.gov.in/ecourtindiaHC/cases/case_no.php?state_cd=6&dist_cd=1&court_code=1&stateNm=Assam",
  GUWAHATI_PARTY:"https://services.ecourts.gov.in/ecourtindiaHC/cases/ki_petres.php?state_cd=6&dist_cd=1&court_code=1&stateNm=Assam",
  HIMACHAL_PRADESH_ADVOCATE:"https://services.ecourts.gov.in/ecourtindiaHC/cases/qs_civil_advocate.php?state_cd=5&dist_cd=1&court_code=1&stateNm=Himachal%20Pradesh",
  HIMACHAL_PRADESH_CASE:"https://services.ecourts.gov.in/ecourtindiaHC/cases/case_no.php?state_cd=5&dist_cd=1&court_code=1&stateNm=Himachal%20Pradesh",
  HIMACHAL_PRADESH_PARTY:"https://services.ecourts.gov.in/ecourtindiaHC/cases/ki_petres.php?state_cd=5&dist_cd=1&court_code=1&stateNm=Himachal%20Pradesh",
  JAMMU_KASHMIR_ADVOCATE:"https://services.ecourts.gov.in/ecourtindiaHC/cases/qs_civil_advocate.php?state_cd=12&dist_cd=1&court_code=1&stateNm=Jammu%20and%20Kashmir",
  JAMMU_KASHMIR_CASE:"https://services.ecourts.gov.in/ecourtindiaHC/cases/case_no.php?state_cd=12&dist_cd=1&court_code=1&stateNm=Jammu%20and%20Kashmir",
  JAMMU_KASHMIR_PARTY:"https://services.ecourts.gov.in/ecourtindiaHC/cases/ki_petres.php?state_cd=12&dist_cd=1&court_code=1&stateNm=Jammu%20and%20Kashmir",
  JHARKHAND_ADVOCATE:"https://services.ecourts.gov.in/ecourtindiaHC/cases/qs_civil_advocate.php?state_cd=7&dist_cd=1&court_code=1&stateNm=Jharkhand",
  JHARKHAND_CASE:"https://services.ecourts.gov.in/ecourtindiaHC/cases/case_no.php?state_cd=7&dist_cd=1&court_code=1&stateNm=Jharkhand",
  JHARKHAND_PARTY:"https://services.ecourts.gov.in/ecourtindiaHC/cases/ki_petres.php?state_cd=7&dist_cd=1&court_code=1&stateNm=Jharkhand",
  KARNATAKA_ADVOCATE:"http://karnatakajudiciary.kar.nic.in/websitenew/casedetails/search_advocatename.php",
  KARNATAKA_CASE:"http://karnatakajudiciary.kar.nic.in/websitenew/casedetails/case_details.php",
  KARNATAKA_PARTY:"http://karnatakajudiciary.kar.nic.in/websitenew/casedetails/search_partyname.php",
  KERALA_ADVOCATE:"https://services.ecourts.gov.in/ecourtindiaHC/cases/qs_civil_advocate.php?state_cd=4&dist_cd=1&court_code=1&stateNm=Kerala",
  KERALA_CASE:"https://services.ecourts.gov.in/ecourtindiaHC/cases/case_no.php?state_cd=4&dist_cd=1&court_code=1&stateNm=Kerala",
  KERALA_PARTY:"https://services.ecourts.gov.in/ecourtindiaHC/cases/ki_petres.php?state_cd=4&dist_cd=1&court_code=1&stateNm=Kerala",
  MADHYA_PRADESH_ADVOCATE:"https://services.ecourts.gov.in/ecourtindiaHC/cases/qs_civil_advocate.php?state_cd=7&dist_cd=1&court_code=1&stateNm=Madhya%20Pradesh",
  MADHYA_PRADESH_CASE:"https://services.ecourts.gov.in/ecourtindiaHC/cases/case_no.php?state_cd=7&dist_cd=1&court_code=1&stateNm=Madhya%20Pradesh",
  MADHYA_PRADESH_PARTY:"https://services.ecourts.gov.in/ecourtindiaHC/cases/ki_petres.php?state_cd=7&dist_cd=1&court_code=1&stateNm=Madhya%20Pradesh",
  MADRAS_ADVOCATE:"https://services.ecourts.gov.in/ecourtindiaHC/cases/qs_civil_advocate.php?state_cd=10&dist_cd=1&court_code=1&stateNm=Madras",
  MADRAS_CASE:"https://services.ecourts.gov.in/ecourtindiaHC/cases/case_no.php?state_cd=10&dist_cd=1&court_code=1&stateNm=Madras",
  MADRAS_PARTY:"https://services.ecourts.gov.in/ecourtindiaHC/cases/ki_petres.php?state_cd=10&dist_cd=1&court_code=1&stateNm=Madras",
  MANIPUR_ADVOCATE:"https://services.ecourts.gov.in/ecourtindiaHC/cases/qs_civil_advocate.php?state_cd=25&dist_cd=1&court_code=1&stateNm=Manipur",
  MANIPUR_CASE:"https://services.ecourts.gov.in/ecourtindiaHC/cases/case_no.php?state_cd=25&dist_cd=1&court_code=1&stateNm=Manipur",
  MANIPUR_PARTY:"https://services.ecourts.gov.in/ecourtindiaHC/cases/ki_petres.php?state_cd=25&dist_cd=1&court_code=1&stateNm=Manipur",
  MEGHALAYA_ADVOCATE:"https://services.ecourts.gov.in/ecourtindiaHC/cases/qs_civil_advocate.php?state_cd=21&dist_cd=1&court_code=1&stateNm=Meghalaya",
  MEGHALAYA_CASE:"https://services.ecourts.gov.in/ecourtindiaHC/cases/case_no.php?state_cd=21&dist_cd=1&court_code=1&stateNm=Meghalaya",
  MEGHALAYA_PARTY:"https://services.ecourts.gov.in/ecourtindiaHC/cases/ki_petres.php?state_cd=21&dist_cd=1&court_code=1&stateNm=Meghalaya",
  ORISSA_ADVOCATE:"https://services.ecourts.gov.in/ecourtindiaHC/cases/qs_civil_advocate.php?state_cd=11&dist_cd=1&court_code=1&stateNm=Odisha/",
  ORISSA_CASE:"https://services.ecourts.gov.in/ecourtindiaHC/cases/case_no.php?state_cd=11&dist_cd=1&court_code=1&stateNm=Odisha/",
  ORISSA_PARTY:"https://services.ecourts.gov.in/ecourtindiaHC/cases/ki_petres.php?state_cd=11&dist_cd=1&court_code=1&stateNm=Odisha/",
  PATNA_ADVOCATE:"https://services.ecourts.gov.in/ecourtindiaHC/cases/qs_civil_advocate.php?state_cd=8&dist_cd=1&court_code=1&stateNm=Patna",
  PATNA_CASE:"https://services.ecourts.gov.in/ecourtindiaHC/cases/case_no.php?state_cd=8&dist_cd=1&court_code=1&stateNm=Patna",
  PATNA_PARTY:"https://services.ecourts.gov.in/ecourtindiaHC/cases/ki_petres.php?state_cd=8&dist_cd=1&court_code=1&stateNm=Patna",
  RAJASTHAN_ADVOCATE:"https://services.ecourts.gov.in/ecourtindiaHC/cases/qs_civil_advocate.php?state_cd=9&dist_cd=1&court_code=1&stateNm=Rajasthan",
  RAJASTHAN_CASE:"https://services.ecourts.gov.in/ecourtindiaHC/cases/case_no.php?state_cd=9&dist_cd=1&court_code=1&stateNm=Rajasthan",
  RAJASTHAN_PARTY:"https://services.ecourts.gov.in/ecourtindiaHC/cases/ki_petres.php?state_cd=9&dist_cd=1&court_code=1&stateNm=Rajasthan",
  SIKKIM_ADVOCATE:"https://services.ecourts.gov.in/ecourtindiaHC/cases/qs_civil_advocate.php?state_cd=24&dist_cd=1&court_code=1&stateNm=Sikkim",
  SIKKIM_CASE:"https://services.ecourts.gov.in/ecourtindiaHC/cases/case_no.php?state_cd=24&dist_cd=1&court_code=1&stateNm=Sikkim",
  SIKKIM_PARTY:"https://services.ecourts.gov.in/ecourtindiaHC/cases/ki_petres.php?state_cd=24&dist_cd=1&court_code=1&stateNm=Sikkim",
  TELANGANA_ADVOCATE:"https://services.ecourts.gov.in/ecourtindiaHC/cases/qs_civil_advocate.php?state_cd=29&dist_cd=1&court_code=1&stateNm=Telangana",
  TELANGANA_CASE:"https://services.ecourts.gov.in/ecourtindiaHC/cases/case_no.php?state_cd=29&dist_cd=1&court_code=1&stateNm=Telangana",
  TELANGANA_PARTY:"https://services.ecourts.gov.in/ecourtindiaHC/cases/ki_petres.php?state_cd=29&dist_cd=1&court_code=1&stateNm=Telangana",
  TRIPURA_ADVOCATE:"https://services.ecourts.gov.in/ecourtindiaHC/cases/qs_civil_advocate.php?state_cd=20&dist_cd=1&court_code=1&stateNm=Tripura",
  TRIPURA_CASE:"https://services.ecourts.gov.in/ecourtindiaHC/cases/case_no.php?state_cd=20&dist_cd=1&court_code=1&stateNm=Tripura",
  TRIPURA_PARTY:"https://services.ecourts.gov.in/ecourtindiaHC/cases/ki_petres.php?state_cd=20&dist_cd=1&court_code=1&stateNm=Tripura",
  UTTARAKHAND_ADVOCATE:"https://services.ecourts.gov.in/ecourtindiaHC/cases/qs_civil_advocate.php?state_cd=15&dist_cd=1&court_code=1&stateNm=Uttarakhand",
  UTTARAKHAND_CASE:"https://services.ecourts.gov.in/ecourtindiaHC/cases/case_no.php?state_cd=15&dist_cd=1&court_code=1&stateNm=Uttarakhand",
  UTTARAKHAND_PARTY:"https://services.ecourts.gov.in/ecourtindiaHC/cases/ki_petres.php?state_cd=15&dist_cd=1&court_code=1&stateNm=Uttarakhand",
  
  


});
module.exports.Proxy= Object.freeze({   
  IP:"176.61.141.229",
  port:"23556",
  username:"ace89",
  password:"MPK3NRU4FJGRTRO28GOAZN4N"
  });

module.exports.AntiCaptcha= Object.freeze({   
  key:"89358358ab7f3d7d910698b1b6384ae3"
  });
  